site_name: Symbiotic Intelligence - Codex
docs_dir: docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal # This should give the "minty" feel
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
plugins:
  - search
  - awesome-pages 